#ifndef __USER_THREAD_MACRO_H__
#define __USER_THREAD_MACRO_H__

const int MSG_TYPE_CAT_HTTP_PLATE_RECOGNITION = 0x10000001;
const int MSG_TYPE_PLATE_RECOGNITION_REQUEST = 0x10000002;
const int MSG_TYPE_PLATE_RECOGNITION_RESPONSE = 0x10000003;

#endif  // __USER_THREAD_MACRO_H__
